### ISSUE TITLE
Error while trying to Make clean pdfium

### ISSUE THREAD

**Issue by anilaphale** [martinlindhe/autofuzz#1]
I am trying to use it with pdfium and got following error:

============================================
Traceback (most recent call last):
  File "./fuzz", line 87, in <module>
    capture_command(cleanCmd)
  File "./fuzz", line 27, in capture_command
    print("    - output: " + e.output)
TypeError: Can't convert 'bytes' object to str implicitly

**Comment by anilaphale** [comment]
Solved this issue by making change:
fuzz.py Line 27

    except subprocess.CalledProcessError as e:
        print("command returned error code " + str(e.returncode))
        print("    - output: " + str(e.output))
        res = e.output
